### PR TITLE
Update defaults.py

### PR DESCRIPTION
**Pull request by fili**

### CODE REVIEW

**Review by abhiabhi94 — COMMENTED** [review]
hey @fili, thanks for taking the time for contributing. as of now, i don't really understand the reason for this change. can you please explain?

if you want to use this website, you can override the defaults in your application settings.

also, this would be a breaking change, so there needs to be some strong reason for it.

**Comment by fili** [comment]
Primary reason for update is higher quality images and more status codes images available. 

The code is not breaking if #3 is incorporated.

**Comment by abhiabhi94** [comment]
> Primary reason for update is higher quality images and more status codes images available.
> 
> The code is not breaking if #3 is incorporated.

is there an issue in overriding the defaults?

**Comment by abhiabhi94** [comment]
> Primary reason for update is higher quality images and more status codes images available.

Thinking more about this, it won't necessarily be a breaking change since people won't be much concerned about the website behind the images, as long as the images are displayed.

Can you please combine all the changes from #3, and #2 here in this patch? it would make more sense to have a feature, its related test and documentation updated in the same patch.

Also, while updating the documentation, can you please make sure we no longer use the images from the earlier website?

Let me know, if you need any help or more clarification regarding this.

**Pull request closed without merging**
